import { useEffect, useState } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { ContactForm } from './components/ContactForm'
import { Seo } from './components/Seo'
import { site } from './constants/site'

const services = [
  ['▰', 'Banery reklamowe', 'Trwałe banery do skutecznej komunikacji w każdym miejscu.'], ['▱', 'Billboardy', 'Wielki format, który buduje widoczność Twojej marki.'], ['▤', 'Wizytówki', 'Pierwsze wrażenie zaklęte w perfekcyjnym detalu.'], ['▧', 'Plakaty', 'Wyraziste komunikaty dla wydarzeń i kampanii.'], ['↥', 'Roll-upy', 'Mobilna ekspozycja gotowa na każde spotkanie.'], ['◎', 'Naklejki', 'Trwałe oznakowanie produktów, witryn i pojazdów.'], ['▱', 'Szyldy', 'Czytelne oznakowanie, które prowadzi do Twojej firmy.'], ['↗', 'Reklama wielkoformatowa', 'Rozwiązania, które działają z naprawdę dużej odległości.'],
]
const reviews = [['Anna K.', 'Marketing Manager', '„Pełen profesjonalizm od projektu po montaż. Nowe oznakowanie naszej siedziby wygląda świetnie.”'], ['Michał P.', 'Właściciel firmy', '„Świetny kontakt, ekspresowa realizacja i bardzo dobra jakość banerów. Zdecydowanie polecam.”'], ['Katarzyna W.', 'Event Coordinator', '„Blockout doskonale zrozumiał naszą wizję. Materiały targowe przyciągały uwagę od pierwszej minuty.”']]
const works = [['Identyfikacja marki', 'druk i ekspozycja'], ['Kampania outdoor', 'wielki format'], ['Materiały eventowe', 'roll-upy'], ['Branding przestrzeni', 'oznaczenia i szyldy']]
const reveal = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0 } }

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) {
  const reduced = useReducedMotion()
  return <motion.div className={className} initial={reduced ? false : 'hidden'} whileInView="visible" viewport={{ once: true, amount: 0.14 }} variants={reveal} transition={{ duration: 0.6, ease: 'easeOut' }}>{children}</motion.div>
}

export default function App() {
  const [openMenu, setOpenMenu] = useState(false); const [scrolled, setScrolled] = useState(false); const [top, setTop] = useState(false); const [activeReview, setActiveReview] = useState(0); const [modal, setModal] = useState<string | null>(null)
  useEffect(() => { const handle = () => { setScrolled(window.scrollY > 20); setTop(window.scrollY > 550) }; handle(); window.addEventListener('scroll', handle, { passive: true }); return () => window.removeEventListener('scroll', handle) }, [])
  useEffect(() => { const timer = window.setInterval(() => setActiveReview((current) => (current + 1) % reviews.length), 5000); return () => window.clearInterval(timer) }, [])
  const menu = [['#o-nas', 'O firmie'], ['#oferta', 'Oferta'], ['#realizacje', 'Realizacje'], ['#opinie', 'Opinie']]
  return <><Seo /><a className="skip-link" href="#content">Przejdź do treści</a>
    <header className={`nav ${scrolled ? 'scrolled' : ''} ${openMenu ? 'open' : ''}`}><div className="container nav-inner"><a className="brand" href="#start" aria-label="Blockout — strona główna">block<i>out</i></a><button className="menu-toggle" type="button" aria-expanded={openMenu} aria-label="Otwórz menu" onClick={() => setOpenMenu(!openMenu)}>☰</button><nav className="nav-links" aria-label="Główna nawigacja">{menu.map(([href, label]) => <a key={href} href={href} onClick={() => setOpenMenu(false)}>{label}</a>)}<a className="button primary nav-cta" href="#kontakt" onClick={() => setOpenMenu(false)}>Porozmawiajmy</a></nav></div></header>
    <main id="content"><section id="start" className="hero"><div className="container hero-grid"><Reveal><span className="eyebrow">Druk & reklama od A do Z</span><h1>Tworzymy reklamę, która <em>przyciąga</em> uwagę.</h1><p className="lead">Projektujemy i produkujemy materiały, które nadają markom wyrazisty, profesjonalny charakter — od wizytówki po wielki format.</p><div className="hero-actions"><a className="button primary" href="#oferta">Zobacz ofertę <span>→</span></a><a className="button ghost" href="#kontakt">Skontaktuj się</a></div><p className="hero-note"><span>●</span> Szybka wycena i indywidualne podejście</p></Reveal><div className="visual" aria-hidden="true"><div className="chip">✦ Jakość, która zostaje</div><div className="print-card poster"><b>MAKE<br />IT<br />VISIBLE.</b><div className="bar" /><div className="circle" /></div><div className="print-card banner"><b>TWOJA<br />MARKA</b><small>zawsze w dobrym świetle</small></div></div></div></section>
      <section id="o-nas" className="section about"><div className="container about-grid"><Reveal><span className="eyebrow">O Blockout</span><h2>Pomysły, które nabierają <em>formatu.</em></h2></Reveal><Reveal><p className="about-copy">Firma Blockout zajmuje się projektowaniem i produkcją profesjonalnych materiałów reklamowych dla firm. Tworzymy rozwiązania, które zwiększają rozpoznawalność marki i pomagają wyróżnić się na rynku.</p><div className="stats">{[['12', 'lat doświadczenia'], ['1200+', 'realizacji rocznie'], ['98%', 'zadowolonych klientów'], ['48h', 'na szybką wycenę']].map(([n, label]) => <div className="stat" key={label}><strong>{n}</strong><span>{label}</span></div>)}</div></Reveal></div></section>
      <section id="oferta" className="section"><div className="container"><Reveal className="section-head"><span className="eyebrow">Nasza oferta</span><h2>Reklama w każdym <em>wymiarze.</em></h2><p className="lead">Od drobnego druku po ekspozycje, których nie da się przeoczyć.</p></Reveal><div className="services">{services.map(([icon, title, text]) => <Reveal key={title} className="service"><div className="service-icon">{icon}</div><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>
      <section className="section why"><div className="container"><Reveal className="section-head"><span className="eyebrow">Dlaczego my</span><h2>Konkretnie. Kreatywnie. <em>Na czas.</em></h2><p className="lead">Łączymy sprawdzoną produkcję z uważnym podejściem do każdej marki.</p></Reveal><div className="why-grid">{['Wysoka jakość', 'Terminowa realizacja', 'Indywidualne projekty', 'Nowoczesne technologie druku', 'Konkurencyjne ceny', 'Doświadczenie'].map((feature) => <Reveal key={feature} className="feature"><span className="check">✓</span>{feature}</Reveal>)}</div></div></section>
      <section id="realizacje" className="section"><div className="container"><Reveal className="section-head"><span className="eyebrow">Realizacje</span><h2>Efekty, które mówią <em>same za siebie.</em></h2><p className="lead">Przykładowe przestrzenie do wypełnienia Twoimi najlepszymi realizacjami.</p></Reveal><div className="gallery">{works.map(([title, kind]) => <button className="work" type="button" key={title} onClick={() => setModal(title)}><span className="work-info">{title}<small>{kind}</small></span></button>)}</div></div></section>
      <section id="opinie" className="section testimonials"><div className="container"><Reveal className="section-head"><span className="eyebrow">Opinie klientów</span><h2>Najlepsza reklama? <em>Zaufanie.</em></h2></Reveal><div className="review"><div className="stars">★★★★★</div><p className="quote">{reviews[activeReview][2]}</p><div className="person">{reviews[activeReview][0]}<span>{reviews[activeReview][1]}</span></div></div><div className="dots">{reviews.map((review, index) => <button key={review[0]} className={`dot ${activeReview === index ? 'active' : ''}`} type="button" aria-label={`Opinia ${index + 1}`} onClick={() => setActiveReview(index)} />)}</div></div></section>
      <section id="kontakt" className="section"><div className="container contact-grid"><Reveal><span className="eyebrow">Kontakt</span><h2>Zróbmy coś, co będzie <em>widać.</em></h2><p className="lead">Opowiedz nam o swoim pomyśle — wrócimy z konkretną propozycją.</p><div className="contact-list"><div className="contact-item"><span>☎</span><div><b>Telefon</b><a href={`tel:${site.phoneHref}`}>{site.phone}</a></div></div><div className="contact-item"><span>✉</span><div><b>E-mail</b><a href={`mailto:${site.email}`}>{site.email}</a></div></div><div className="contact-item"><span>⌖</span><div><b>Adres</b><address>{site.address}</address></div></div></div></Reveal><Reveal><ContactForm /></Reveal></div></section></main>
    <footer><div className="container"><div className="footer-row"><a className="brand footer-brand" href="#start">block<i>out</i></a><div className="socials"><a href="#kontakt" aria-label="Facebook">fb</a><a href="#kontakt" aria-label="Instagram">ig</a><a href="#kontakt" aria-label="LinkedIn">in</a></div></div><p className="copyright">© {new Date().getFullYear()} Blockout. Wszystkie prawa zastrzeżone.</p></div></footer>
    <button className={`to-top ${top ? 'show' : ''}`} type="button" aria-label="Powrót do góry" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>↑</button>
    {modal && <div className="modal" role="dialog" aria-modal="true" aria-label={`Podgląd: ${modal}`} onClick={() => setModal(null)}><div className="modal-body" onClick={(event) => event.stopPropagation()}><button className="close" type="button" aria-label="Zamknij" onClick={() => setModal(null)}>×</button><strong>{modal}</strong></div></div>}
  </>
}
